config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    mount ActionCable.server, at: '/cable'
    root to: 'pages#home'

    get '/home', to: 'pages#home'

    scope :post do
        get  '/new-post',    to: 'posts#new_post'
        post '/create-post', to: 'posts#create_post'
    end

    scope :chat_room, as: :chat_room do
        get '/home',         to: 'chat_room#home_chat_room'
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chat_room_controller.rb
class ChatRoomController < ApplicationController
    def home_chat_room
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @posts = Post.all
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new_post
        @post = Post.new
    end

    def create_post
        Post.create!(post_params)
        redirect_to root_path
    end

    private

    def post_params
        params.require(:post).permit(
            :caption,
            :image
        ) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat_room/home_chat_room.html.erb
<div class="container-element home--chat--room">
    <h1>Public Chat Room</h1>
    <section class="chat--section">
        <div class="chat--section__messages">
            <%# <div class="message">
                <div class="username">Sender: Monk</div>
                <div class="content">Message: noice noice noice noice noice</div>
            </div> %>
        </div>

        <div class="chat--section__button--container">
            <input 
                type="text" 
                id="chat-message"
                data-controller="chat_room"
                data-handler="send_message">
            <button 
                class="chat--section__send"
                data-controller="chat_room"
                data-handler="send_message"
                >Send</button>
        </div>

        <div class="chat--section__nickname--container">
            <label for="nickname">
                <span>Nicekname</span>
                <input 
                    type="text" 
                    placeholder="Enter Nickname" 
                    value="Anon" 
                    id="nickname">
            </label>
        </div>
    </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Count Dokku</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application' %>
        <link href="https://fonts.googleapis.com/css?family=Muli:400,500,600,700,800,900&display=swap" rel="stylesheet">
    </head>

    <body>
        <%= yield %>
    </body>
</html>

app/views/pages/home.html.erb
<div class="container-element">
    <h1 class="home--header">Welcome to Count Dokku</h1>
    <div class="add--posts">
        <%= link_to 'Add New Post', new_post_path %>
        <br>
        <%= link_to 'Chat Room', chat_room_home_path %>
    </div>
    <section class="posts">
        <% @posts.each do |post| %>
            <figure class="post--item">
                <div class="image--container">
                    <%= image_tag post.image_url %>
                </div>
                <figcaption>Caption: <%= post.caption %></figcaption>
            </figure>
        <% end %>
    </section>
</div>

app/views/posts/new_post.html.erb
<div class="container-element">
    <h1>Add New Post</h1>
    <section class="add--post--section">
        <%= form_for @post, url: create_post_path do |f| %>
            <label for="post_caption">
                <span>Caption: </span>
                <%= f.text_field :caption %>
            </label>
            <label for="post_image">
                <span>Image: </span>
                <%= f.file_field :image %>
            </label>
            <%= f.submit 'Submit' %>
        <% end %>
    </section>
</div>